project_id = "fbpzvcixoocdtzqvtwfr"

[functions.admin-create-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-list-users]
verify_jwt = true

[functions.admin-update-user]
verify_jwt = true

[functions.export-data]
verify_jwt = true

[functions.import-data]
verify_jwt = true

[functions.reset-app]
verify_jwt = true

[functions.restore-admin]
verify_jwt = true

[functions.woocommerce-import]
verify_jwt = true

[functions.woocommerce-sync]
verify_jwt = true